### ISSUE TITLE
Action Server running in --expose mode does not allow action runs via UI running on localhost, instead of getting 403 guide the user

### ISSUE THREAD

**Issue by kariharju** [robocorp/robocorp#347] opened 2024-04-11 14:28 UTC
### Target components

action_server

### What is wrong

1. On local machine take the template action project
2. `action-server start --exposed`
3.  Open the UI from the localhost url provided
4.  Try to run an action

Result: User gets 403 error

Reason:
In exposed more the actions can be called via the exposed API and as the authentication is on, triggering runs from localhost are blocked.

Proposed fix:
We should make this obvious on the UI: "Action Server is running in exposed mode, local runs are blocked"

Later on we can figure out if it would be secure to enable this access for development purposes.

### System info

Any action-server version.

**Comment by fabioz** [comment] 2024-04-12 11:32
As a note, I can't really reproduce this and this should work (provided that the api key is given).

i.e.:

![image](https://github.com/robocorp/robocorp/assets/117621/b2837369-d25b-460a-8494-3abbd07e5f75)

**Comment by fabioz** [comment] 2024-04-12 11:35
Although the error I get when the api key is not given is a bit different (so, maybe this is something else?)

![image](https://github.com/robocorp/robocorp/assets/117621/00b499b9-9068-4d82-8f28-c357eacd802d)

**Comment by fabioz** [comment] 2024-05-27 13:24
This seems to be the same issue reported in https://github.com/robocorp/robocorp/issues/357, so, closing this one.

**Closed as completed by fabioz** 2024-05-27 13:24 UTC
Labels: Bug, Action Server
